### ISSUE TITLE
Dead link (to linked panes) in the Workspace note

### ISSUE THREAD

**Issue by StrangeGirlMurph** [obsidianmd/obsidian-developer-docs#113]
The broken link: https://help.obsidian.md/User+interface/Workspace/Panes/Linked+pane

Found here: 
https://github.com/obsidianmd/obsidian-developer-docs/blob/3e2c87057d59bdbe7c93aca7157b42c72e77a747/en/Plugins/User%20interface/Workspace.md?plain=1#L130

**Comment by joethei** [comment]
This has now been fixed.
