### ISSUE TITLE
[Graph View] - Restore Default Settings button do not reset 'groups' on live view

### ISSUE THREAD

**Issue by MRGuziX** [obsidianmd/obsidian-developer-docs#123]
### Build 
1.6.5
### Reproduction Steps
1. Open Graph View
2. Add note
3. Add some word to it like "kastor" 
4. Open cog wheel of Graph View
5. Create group based on that word "kastor" -> Now we can see that 'dot' was colored
6. click "reset default settings' button
![image](https://github.com/obsidianmd/obsidian-developer-docs/assets/52559706/2d6fb016-f18e-49b1-9e80-3f89ece0b81e)

### Actual Result
Group was removed, but dot it is still colored
![image](https://github.com/obsidianmd/obsidian-developer-docs/assets/52559706/34dff2c0-c4aa-4227-99a0-6e72a18ebe4f)

### Expected Result
Probably it should be updated live. When you close Graph View and open it again things is updated

### Notes
Problably it is cached somewhere. When you delete group directly it is updated live.

**Comment by joethei** [comment]
This is the repository for our theme/plugin development documentation.
Please post issues/feature requests on our forum: <https://forum.obsidian.md> and follow the template there.
