### ISSUE TITLE
[Feature Request[ - Creating notes and folders by clicking RMB on Catalog Tree

### ISSUE THREAD

**Issue by MRGuziX** [obsidianmd/obsidian-developer-docs#124]
### Description

Hey Obsydian Team :)

It would be nice to add this kind of feature to project. Because from user perspective it is pretty obvious that RMB it is doing SOMETHING. In daily life clicking RMB is giving us some popup menu from which you can pick something.

Here you could add some options to do (even clone then from the action bar above)
![image](https://github.com/obsidianmd/obsidian-developer-docs/assets/52559706/808f9e36-e4d8-486c-a798-2a203f2bc3f3)

### UX:
Hover mouse over Catalog Tree space (long grey column)
If over item -> Show actions on item
If over empty space -> dropdown menu : Create note, Create folder

**Comment by joethei** [comment]
This is the repository for our theme/plugin development documentation.
Please post issues/feature requests on our forum: <https://forum.obsidian.md> and follow the template there.
