### ISSUE TITLE
Glitchy markdown?

### ISSUE THREAD

**Issue by RoyalCoderPRO** [obsidianmd/obsidian-developer-docs#126]
https://github.com/obsidianmd/obsidian-developer-docs/assets/87411629/2ab19cc8-f623-4241-98db-fa09ba78e5d6

The reading view doesn't seem to be consistent with the edit view with tab spaced checkboxes (with numeric listing)

(Using typewriter theme, if that somehow makes a difference?)

**Comment by joethei** [comment]
This is the repository for our developer facing documentation.
Please post issues on our forum: <https://forum.obsidian.md> and follow the bug report template there.
