### ISSUE TITLE
Add MetadataTypeManager to App interface

### ISSUE THREAD

**Issue by b-camphart** [obsidianmd/obsidian-developer-docs#129]
In trying to make my plugin work with properties that users haven't yet explicitly defined, I found myself investigating how obsidian is tracking them, and found the `metadataTypeManager` property in the `app`.

You can see in [this file from my plugin](https://github.com/b-camphart/timeline-view/blob/main/src/obsidian/MetadataTypeManager.ts) how I'm defining the interface for it myself, and checking that it's of the appropriate shape before using it.  However, it would be nice to have this fully documented and made available from the obsidian api.  I'd be willing to adapt some of the linked documentation/interfaces for the official api.

**Comment by joethei** [comment]
Private APIs are not documented because they are private.
There are loads of methods and fields that exists at runtime but aren't in the API because we have not committed to supporting them through the API.

**Comment by brendan-attnl** [comment]
I had a feeling.  I was loading in the types.json file before, but that only has explicitly registered properties.  I'm guessing there's no other, official way to query for properties?
