### ISSUE TITLE
Typo on getActiveFile.md

### ISSUE THREAD

**Issue by sanchezg7** [obsidianmd/obsidian-developer-docs#130]
Per the contributing guidelines, I'm submitting an issue as opposed to a PR that fixes the issue. There is a typo in getActiveFile.md@14

---

Current: `Otherwise, it will recent the most recently active file.`
Proposed: `Otherwise, it will reopen the most recently active file.`

**Comment by liamcain** [comment]
Thanks! Fixed upstream in the API docstring; will get updated in the developer docs the next time we publish the API.

**Comment by liamcain** [comment]
In the next publishing of the API, this will be:

> Otherwise, it will return the most recently active file
