### ISSUE TITLE
Make vault.rename() docs point to FileManager.renameFile()

### ISSUE THREAD

**Issue by claremacrae** [obsidianmd/obsidian-developer-docs#133]
## Background

This crops up on Discord periodically:

For example, from @zsviczian [on Discord today](https://discord.com/channels/686053708261228577/840286264964022302/1267428882693361664):

> It appears as if app.vault.rename (file, newpath) does not honor "Automatically update internal links". Do you know if this is by design or this is a bug? How should I rename files instead?

The answer is always to use https://docs.obsidian.md/Reference/TypeScript+API/FileManager/renameFile

## Suggestion:

In https://docs.obsidian.md/Reference/TypeScript+API/Vault/rename:
- add a note that it does not update links to the file being renamed
- and say to use https://docs.obsidian.md/Reference/TypeScript+API/FileManager/renameFile instead...

**Comment by liamcain** [comment]
Done: https://docs.obsidian.md/Reference/TypeScript+API/Vault/rename
