### ISSUE TITLE
Obisidan starts once after snap install, no help debugging, strace breaks root. Newest Ubuntu 24.04

### ISSUE THREAD

**Issue by cgthayer** [obsidianmd/obsidian-developer-docs#134]
***Expected***

First, let me say that this is quite probably about the AppArmor on Ubuntu 24.04 and not about Obsidian itself.

Installed obsidian on fresh ubuntu 24.04 install with `sudo snap install obsidian --classic` and it ran once, but then wouldn't restart. It produced no output, and exited with a exit code 1. There's no output and all debug cmd-line options don't seem to work.

***Happened***

Trying to get some info I tried, but the output was always empty

```
:::: graphite 10:49:03 0 work; obsidian --help
:::: graphite 10:49:06 0 work; obsidian help
:::: graphite 10:49:09 0 work; obsidian -v
:::: graphite 10:49:12 0 work; obsidian -d
```

When it runs once it has some trouble, then it won't restart:

```
:::: graphite 10:59:11 0 work; obsidian
2024-08-06 17:59:14 Loading main app package /snap/obsidian/35/resources/obsidian.asar
Ignored: Error: ENOENT: no such file or directory, open '/home/thayer/snap/obsidian/35/.config/obsidian/obsidian.json'
2024-08-06 17:59:14 Checking for update using Github
2024-08-06 17:59:14 Success.
2024-08-06 17:59:14 Latest version is 1.6.7
2024-08-06 17:59:14 App is up to date.
[7216:0806/105916.052334:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[7216:0806/105917.144454:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
Ignored: Error: ENOENT: no such file or directory, open '/home/thayer/snap/obsidian/35/.config/obsidian/9d27f738ad629670.json'
```

I also tried to strace it, which requires root privileges. It seemed to want certain directories in "/root" like "Desktop" and then it created symlinks that looped back to themselves:

```
:::: graphite 10:44:22 0 work; sudo strace -o trace.out -f obsidian
[sudo] password for thayer: 
realpath: /root/Documents: Too many levels of symbolic links
:::: graphite 10:44:41 0 work; sudo bash
root@graphite:/home/thayer/work# cd
root@graphite:~# pwd
/root
root@graphite:~# ls -l
total 4
lrwxrwxrwx 1 root root   13 Aug  6 10:36 Desktop -> /root/Desktop
lrwxrwxrwx 1 root root   15 Aug  6 10:36 Documents -> /root/Documents
lrwxrwxrwx 1 root root   15 Aug  6 10:36 Downloads -> /root/Downloads
lrwxrwxrwx 1 root root   11 Aug  6 10:36 Music -> /root/Music
lrwxrwxrwx 1 root root   14 Aug  6 10:36 Pictures -> /root/Pictures
lrwxrwxrwx 1 root root   12 Aug  6 10:36 Public -> /root/Public
drwx------ 8 root root 4096 Aug  6 10:44 snap
lrwxrwxrwx 1 root root   15 Aug  6 10:36 Templates -> /root/Templates
lrwxrwxrwx 1 root root   12 Aug  6 10:36 Videos -> /root/Videos
root@graphite:~# rm Desktop Documents Downloads Music Pictures Public Templates Videos 
root@graphite:~# ls snap
firefox  firmware-updater  obsidian  snapd-desktop-integration  snap-store  thunderbird
root@graphite:~# ls snap/obsidian/
35  common  current
root@graphite:~# ls -lR snap/obsidian/
snap/obsidian/:
total 8
drwxr-xr-x 4 root root 4096 Aug  6 10:44 35
drwxr-xr-x 3 root root 4096 Aug  6 10:44 common
lrwxrwxrwx 1 root root    2 Aug  6 10:44 current -> 35

snap/obsidian/35:
total 0

snap/obsidian/common:
total 0
root@graphite:~# 
```

***Should Happen***

I'd expect that obsidian would have a way to debug failures, but it's unclear to me if this is a `snap` issue or `AppArmor` or Obsidian.

***Workaround and Notes***

* I removed and re-installed several times with `sudo snap remove --purge obsidian`
* Using the `*.deb`with `sudo dpkg -i FILE` worked for me.

**Comment by sigrunixia** [comment]
Hello @cgthayer,

This is the repository for our developer documentation help site, which contains resources for making community plugins and themes. 

For assistance with the application, I will need to refer you to our Obsidian Community (https://obsidian.md/community). In particular, since it is Ubuntu you are experiencing this on, you may find the best help on our Discord, in the #off-topic thread labeled `Linux people doing Linux things`.
