### ISSUE TITLE
`this.manifest.dir` is not listed among Manifest properties

### ISSUE THREAD

**Issue by nicholas-wilcox** [obsidianmd/obsidian-developer-docs#139]
https://docs.obsidian.md/Reference/Manifest

**Comment by lishid** [comment]
Correct. It is not listed because it's not part of the manifest file. It is present at runtime as a private API.

**Comment by nicholas-wilcox** [comment]
@lishid IMO, this shouldn't be a private API. I was just told in a code review for my own plugin that I should use `this.manifest.dir` instead of computing it myself. If this is something that developers of plugins should know about, then it should be present in the developer documentation.

**Comment by liamcain** [comment]
`dir` is not a private API. It is listed here: <https://github.com/obsidianmd/obsidian-api/blob/df9434bec6883bd32727f61b1ed1336f7663d0e4/obsidian.d.ts#L3102>

**Comment by lishid** [comment]
Ah haha I totally forgot.

**Comment by nicholas-wilcox** [comment]
oh yeah, I can discover it just fine in the code with LSP.
