### ISSUE TITLE
Minor errors in a "Understanding deferred views" example

### ISSUE THREAD

**Issue by RyotaUshio** [obsidianmd/obsidian-developer-docs#145]
Thanks for the new plugin guide pages. I found a small typo where the line in the middle of the 2nd code block of this page https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views lacks `.first()`  (and also the `leaf !== undefined` check).

Also the first line is a bit confusing because the `leaf` variable (which is either `WorkspaceLeaf` or `undefined`) is type-asserted as a view.

I suppose you meant something like this?

```ts
// Bad
let leaf = workspace.getLeavesOfType('my-view').first();
let view = leaf?.view as MyCustomView;
...

// Good
let leaf = workspace.getLeavesOfType('my-view').first();
if (leaf?.view instanceof MyCustomView) {
    ...
}
```

**Comment by RyotaUshio** [comment]
I saw the example updated, but in the line `let view = leaf.first() as MyCustomView;` in the "Bad" example, i hink `first()` should be `view` instead.

**Comment by lishid** [comment]
Good catch, thank you!
