### ISSUE TITLE
`ButtonComponent` ref is missing

### ISSUE THREAD

**Issue by IdanLib** [obsidianmd/obsidian-developer-docs#151]
Hi Obsidian

The ref for the `ButtonComponent` is missing. It needs to be added so people like me will have more clarity when developing plugins.

![Screenshot from 2024-10-05 23-56-58](https://github.com/user-attachments/assets/328ec909-d60c-4310-a814-8e9cfbe7a0b5)

**Comment by joethei** [comment]
Fixed, not sure why it disappeared.
