### ISSUE TITLE
Remove index in reference docs

### ISSUE THREAD

**Issue by marcusolsson** [obsidianmd/obsidian-developer-docs#23]
https://docs.obsidian.md/Reference/TypeScript+API/index doesn't add much, but removing it breaks the breadcrumb in all the pages. 

To remove it, we also need to remove the "Home" link in every page.

<img width="631" alt="Screenshot 2023-04-28 at 18 10 43" src="https://user-images.githubusercontent.com/8396880/235199243-de383a00-769b-41ac-b392-b6a4a67abd30.png">

**Comment by ericaxu** [comment]
Is this already fixed by my patch on the API documenter? See: https://docs.obsidian.md/Reference/TypeScript+API/BaseComponent/setDisabled

"Home" and "obsidian" shouldn't be showing up any more.

If so, we can close this.
