### ISSUE TITLE
Fix the logo on mobile

### ISSUE THREAD

**Issue by marcusolsson** [obsidianmd/obsidian-developer-docs#25]
<img width="487" alt="Screenshot 2023-04-28 at 18 13 31" src="https://user-images.githubusercontent.com/8396880/235199774-ff1c0b4d-e409-462e-a574-0e69b7ba3140.png">

**Comment by ericaxu** [comment]
Hmm what's the status of this, do you need help fixing it? I can help if you need.

**Comment by ericaxu** [comment]
Already fixed as of Aug 4.
