### ISSUE TITLE
Add a GitHub link to modify docs

### ISSUE THREAD

**Issue by LBF38** [obsidianmd/obsidian-developer-docs#41]
Hi there, 

In the process of creating a plugin and obviously, Obsidian docs is the way to go !
And I was thinking that it could be great to have an external link at the bottom of each note, so that readers that spot something can easily report it in GitHub and therefore, enhance the documentation.
Even though you've probably already thought of it ! 😄 
It could be a simple link like the ones in [Marcus Olsson's unofficial documentation](https://marcus.se.net/obsidian-plugin-docs/).

Have a nice day !

**Comment by ericaxu** [comment]
Marcus's site uses Docusaurus (iirc, might be wrong) which has this feature built in. Unfortunately it's a lot harder for us to do; that would be a feature request for Obsidian Publish, unless we run a script to append a note to each note ourselves.

I've added a link in the home page instead. Hope that helps! https://github.com/obsidianmd/obsidian-developer-docs/commit/80450d3c0d74596d37fe085eb2d960311f618ee2
