### ISSUE TITLE
markdown postProcessor

### ISSUE THREAD

**Issue by 1C0D** [obsidianmd/obsidian-developer-docs#61]
Help lets think it's working in preview mode registerMarkdownPostProcessor
but it's only in reading mode. If I'm right about how to call it
https://docs.obsidian.md/Plugins/Editor/Markdown+post+processing

**Comment by 1C0D** [comment]
and parameters seems to be totally different from the example
registerMarkdownPostProcessor(postProcessor: MarkdownPostProcessor, sortOrder?: number): MarkdownPostProcessor;

**Comment by 1C0D** [comment]
@lishid ok good but why parameters are so different from what is given by the API ?

**Comment by lishid** [comment]
The parameter is correct in the example. The API is an interface-function and we are not making use of the optional parameter in the example.

**Comment by 1C0D** [comment]
ok because of the structure of the interface MarkdownPostProcessor
I have still some lack in TS. but a link to it will be good in the API ? and the doc ?
