### ISSUE TITLE
`MarkdownRenderer.renderMarkdown()` was deprecated

### ISSUE THREAD

**Issue by abiriadev** [obsidianmd/obsidian-developer-docs#64]
## Expected result

The type definition [here](https://github.com/obsidianmd/obsidian-api/blob/249eb773347588f4e9fec7c600e1904cd9240fcb/obsidian.d.ts#L2230-L2245) says that `MarkdownRenderer.renderMarkdown()` is deprecated. Also, it suggests using the `MarkdownRenderer.render()` method instead.

## Actual result

The official documentation for [`MarkdownRenderer`](https://docs.obsidian.md/Reference/TypeScript+API/MarkdownRenderer/MarkdownRenderer) neither mentions this deprecation nor provides documentation for `render()` method.

It would be great if the official doc could address these issues.

Regards.

## Reference

 * [obsidian forum](https://forum.obsidian.md/t/markdownrenderer-does-not-have-a-proper-document/67893)

**Comment by joethei** [comment]
Published a new version of the docs which mentions this, the `render` method is also now included in the docs.
