### ISSUE TITLE
"Contributing" doesn't mention limits (also, there are limits)

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-developer-docs#68]
https://docs.obsidian.md/Home#Contributing invites readers to contribute to the docs, but apparently at least some of them are auto generated and can't be contributed to. Ideally they should be open to contributions, but at minimum it should be clear up front what is and what isn't to avoid wasting time, effort, and goodwill as happened here: https://forum.obsidian.md/t/where-are-the-developer-docs-people-are-praising/65982/14?u=cawlinteffid

**Comment by sigrunixia** [comment]
Adding the status of this to #40.
