### ISSUE TITLE
`Workspace.getLeafById` is mistyped

### ISSUE THREAD

**Issue by RyotaUshio** [obsidianmd/obsidian-developer-docs#72]
The documentation (https://docs.obsidian.md/Reference/TypeScript+API/Workspace/getLeafById) says
```ts
getLeafById(id: string): WorkspaceLeaf;
```
But if `id` is just a random string, it returns `null`. So instead it should be 
```ts
getLeafById(id: string): WorkspaceLeaf | null;
```

**Comment by joethei** [comment]
Thanks

**Comment by joethei** [comment]
Deployed
