### ISSUE TITLE
`resolveSubPath` is mistyped

### ISSUE THREAD

**Issue by RyotaUshio** [obsidianmd/obsidian-developer-docs#73]
The [documentation](https://docs.obsidian.md/Reference/TypeScript+API/resolveSubpath) says that it returns either `HeadingSubpathResult` or `BlockSubpathResult`, but it can return `null` for an invalid `subpath`.

**Comment by liamcain** [comment]
Thanks!

**Comment by joethei** [comment]
Fixed version deployed.
