### ISSUE TITLE
<iframe> tag returns "<!DOCTYPE "... is not valid JSON." 

### ISSUE THREAD

**Issue by AngelicaRibeiro** [obsidianmd/obsidian-developer-docs#74]
Bug Report

Description:
I attempted to import a GitHub project into an Obsidian markdown file using the <iframe> tag. However, whenever I tried to edit something in the rendered page, I encountered the following error: Unexpected token '<', "<!DOCTYPE "... is not valid JSON.

Steps to Reproduce:

Open an Obsidian markdown file.
Insert the GitHub project using the <iframe> tag.
Attempt to edit content within the rendered page.
Expected Behavior:
I should be able to edit content in the rendered page without encountering any errors.

Actual Behavior:
Encountered the error Unexpected token '<', "<!DOCTYPE "... is not valid JSON whenever attempting to edit the rendered content.

Additional Information:

Obsidian version: 1.4.16
Browser: Google Chrome
Operating System: 
    DISTRIB_ID="ManjaroLinux"
    DISTRIB_RELEASE="23.0.4"
    DISTRIB_CODENAME="Uranos"
    DISTRIB_DESCRIPTION="Manjaro Linux"

Screenshots:

![Screenshot_20231015_123409](https://github.com/obsidianmd/obsidian-developer-docs/assets/13433634/5bcd81d3-34f0-4e58-9d5a-b8fec0e646ff)

Thank you for your attention to this matter!

**Comment by sigrunixia** [comment]
Hello @AngelicaRibeiro,

This is the developer documentation repository. Please make any bug reports on the application on [our forum](https://forum.obsidian.md/c/bug-reports/7) instead.
