### ISSUE TITLE
The `AbstractInputSuggest` page is incorrectly rendered

### ISSUE THREAD

**Issue by RyotaUshio** [obsidianmd/obsidian-developer-docs#79]
The `<input>` in the docstring is rendered as an input form in the dev docs.

Docstring:

https://github.com/obsidianmd/obsidian-api/blob/249eb773347588f4e9fec7c600e1904cd9240fcb/obsidian.d.ts#L284-L290C23

```ts
/**
 * Attach to an <input> element or a <div contentEditable> to add type-ahead
 * support.
 *
 * @public
 */
export abstract class AbstractInputSuggest<T> extends PopoverSuggest<T> {
```

Result:

https://docs.obsidian.md/Reference/TypeScript+API/AbstractInputSuggest

<img width="761" alt="image" src="https://github.com/obsidianmd/obsidian-developer-docs/assets/72342591/9c4d14e7-09a7-4722-b0bb-30bdd7265187">

**Comment by joethei** [comment]
Thanks

**Comment by joethei** [comment]
Deployed
