### ISSUE TITLE
`AbstractInputSuggest`'s `getSuggestions` method is undocumented

### ISSUE THREAD

**Issue by RyotaUshio** [obsidianmd/obsidian-developer-docs#80]
If I understand correctly, `AbstractInputSuggest` doesn't work without defining ~~`getSuggestion`~~`getSuggestions`, just as `SuggestModal` (https://docs.obsidian.md/Reference/TypeScript+API/SuggestModal).

However, this method seems to be undocumented:
https://docs.obsidian.md/Reference/TypeScript+API/AbstractInputSuggest

Am I missing anything? Thank you.

**Comment by danielo515** [comment]
The method is named getSuggestions, but yeah, absolutely

**Comment by liamcain** [comment]
Thanks, this will be fixed when we publish the new API spec.

**Comment by RyotaUshio** [comment]
Thank you!

**Comment by joethei** [comment]
Published
