### ISSUE TITLE
Mixed messages in UI > Commands > Hot keys

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-developer-docs#81]
The main text of https://docs.obsidian.md/Plugins/User+interface/Commands#Hot+keys feels somewhat at odds with its warning callout. The warning essentially says, "You can do this, but don't (unless it's for your private personal use)." That feels like a strong enough message that it deserves to be mentioned in the first paragraph, too.

Of course if developers aren't generally assigning hotkeys then it's probably fine as-is.

**Comment by ericaxu** [comment]
I feel that's okay, the first "you can" is more like you have the ability to in case it makes senses, but we don't recommend it.

Has there been confusion over this?

**Comment by colintedford** [comment]
Not that I know of. I ended up at that page when someone asked if there were ranges of hotkeys that were recommended to avoid assigning by default.
