### ISSUE TITLE
The `registerMarkdownCodeBlockProcessor` is incorrectly rendered

### ISSUE THREAD

**Issue by noxonad** [obsidianmd/obsidian-developer-docs#82]
The `<pre>`, `<code>` and `<div>` tags are incorrectly rendered, cutting the following text after.

Docstring:

https://github.com/obsidianmd/obsidian-api/blob/249eb773347588f4e9fec7c600e1904cd9240fcb/obsidian.d.ts#L2941
```ts
/**
 * Register a special post processor that handles fenced code given a language and a handler.
 * This special post processor takes care of removing the <pre><code> and create a <div> that
 * will be passed to the handler, and is expected to be filled with custom elements.
 * @see {@link https://docs.obsidian.md/Plugins/Editor/Markdown+post+processing#Post-process+Markdown+code+blocks}
 * @public
 */
registerMarkdownCodeBlockProcessor(language: string, handler: (source: string, el: HTMLElement, ctx: MarkdownPostProcessorContext) => Promise<any> | void, sortOrder?: number): MarkdownPostProcessor;
```

Result:

https://docs.obsidian.md/Reference/TypeScript+API/Plugin/registerMarkdownCodeBlockProcessor

![image](https://github.com/obsidianmd/obsidian-developer-docs/assets/130460440/e9105a5a-5cd6-4c4c-ae74-68eaf1dabb40)

**Comment by lishid** [comment]
Will be fixed by https://github.com/obsidianmd/obsidian-api/commit/cdc74f2c3b245abc20e71e6ca996ea21e9fd1a13 once we publish it, thanks!
