### ISSUE TITLE
Variable definition code sample error in Views page

### ISSUE THREAD

**Issue by daledesilva** [obsidianmd/obsidian-developer-docs#85]
In this page:
https://docs.obsidian.md/Plugins/User+interface/Views

One of the code blocks shows:
```ts
let leaf = workspace.getRightLeaf(false);
```

but it shouldn't have the `let` and produces and error because the variable leaf should be used from the one defined outside the if statement.

full code:
```ts
async activateView() {
	let { workspace }  = this.app;

	let leaf: WorkspaceLeaf | null = null;
	let leaves = workspace.getLeavesOfType(VIEW_TYPE_EXAMPLE);

	if (leaves.length > 0) {
		// A leaf with our view already exists, use that
		leaf = leaves[0];
	} else {
		// Our view could not be found in the workspace, create a new leaf
		// in the right sidebar for it
		let leaf = workspace.getRightLeaf(false);
		await leaf.setViewState({ type: VIEW_TYPE_EXAMPLE, active: true });
	}

	// "Reveal" the leaf in case it is in a collapsed sidebar
    workspace.revealLeaf(leaf);
  }
```

**Comment by lishid** [comment]
Thanks, would you like to send a PR for it for attribution?

**Comment by daledesilva** [comment]
Sure. I'll do it later today.

For future reference...If I find others should I jump straight to the PR?
If so, any thoughts on threshold for which an issue is needed first?
ie.
Typo -> PR
Code error -> PR
Minor suggestion of addition to help reader -> PR?
Some bigger thing/suggestion -> Create issue first.

**Comment by lishid** [comment]
If you are confident they are just typos/minor corrections, and are likely to be accepted, I think it's ok to just send PRs. If you're making big changes that take effort, and might be controversial then I suggest making an issue first to see if everyone agrees with the change.
