### ISSUE TITLE
"Use Svelte in your plugin" is outdated

### ISSUE THREAD

**Issue by yan42685** [obsidianmd/obsidian-developer-docs#92]
The command `npm install --save-dev svelte svelte-preprocess @tsconfig/svelte esbuild-svelte` installs the latest version of Svelte (4.0), which may introduce a number of additional issues. My current solution is to reference previous code repositories to use dependencies related to version 3.0.

[Doc link](https://docs.obsidian.md/Plugins/Getting+started/Use+Svelte+in+your+plugin)

**Comment by joethei** [comment]
The docs have now been updated to use Svelte 5
