### ISSUE TITLE
Default github actions needs clarification and perhaps further permissions

### ISSUE THREAD

**Issue by nicolello-dev** [obsidianmd/obsidian-developer-docs#93]
I had never used GitHub actions before creating my plugin, tho I already knew what it was about.

When submitting my plugin, the github action specified in the docs was not working because it needed further permissions to access the `GITHUB_REF`; [see my first run](https://github.com/nicolello-dev/Obsidian-nerd-stats/actions/runs/7433711033/job/20227059236).

I don't know what the best approach is to this,. I'm aware my solution is not the best, but I gave it all permissions I could think of, both on the workflow itself as (`packages: write`)[https://github.com/nicolello-dev/Obsidian-nerd-stats/blob/6aedaea0e80fb931c190b130c57265e9ef07f6b2/.github/workflows/release.yaml#L11] and through `settings > actions > general > workflow permissions > read and write permissions`.

**Comment by joethei** [comment]
Instructions for this have now been added.
